site_name: tatva
site_description: The documentation for the tatva software package
site_author: David BÃ¼eler

repo_url: https://github.com/smec-ethz/tatva
repo_name: GitHub

nav:
  - Home: index.md
  - About: about.md

theme: material
